### ISSUE TITLE
Lang Switcher

### ISSUE THREAD

**Issue by haroldao** [prismicio-community/eleventy-plugin-prismic#11]
Hey the team.

Is there a way to create a lang switcher ?

**Comment by lihbr** [comment]
Hey there,

I'm not completely sure I get your request, but you should be able to create a lang switcher by looping over your document's alternate languages, something like so:

```njk
<ul>
{% for alternateDocument in document.alternate_languages %}
	<li>
	{% link alternateDocument %}
		{{ alternateDocument.lang }}
	{% endlink %}
	</li>
{% endfor %}
</ul>
```

For this case, you'd have to rely on the link resolver though (unfortunately the route resolver doesn't work with alternate language documents yet): https://github.com/prismicio-community/eleventy-plugin-prismic/blob/master/DOCUMENTATION.md#interface

Let me know :)

**Comment by haroldao** [comment]
Okay. Ty Lucie. I'll try that☺️
