### ISSUE TITLE
Access to multiple languages

### ISSUE THREAD

**Issue by enbee81** [prismicio-community/eleventy-plugin-prismic#6]
When I create a Custom Type with multiple languages, I don't see a way to get access to languages other than the main language. I tried `{{ prismic.author | dump | safe }}` to see all the fetched content, but I only get the main language's content.

Maybe I am missing something here.

**Comment by lihbr** [comment]
OK, so I can confirm the plugin doesn't support multiple languages as of talking. I'm working on a solution to that today ☺️

**Comment by lihbr** [comment]
Just released that as part of `0.1.5` as an experimental feature 🎉

By experimental I mean that breaking changes might be introduced under that feature scope should we discover the implemented interface is not ideal.

Documentation has been updated accordingly: https://github.com/prismicio-community/eleventy-plugin-prismic/blob/master/DOCUMENTATION.md#i18n-experimental

I'm really interested in your feedback about it! Please HMU on Twitter or here if you'd like to share anything ☺️
