### ISSUE TITLE
Notation with Liquid

### ISSUE THREAD

**Issue by haroldao** [prismicio-community/eleventy-plugin-prismic#8]
Hey !

Is it normal I have to write for example : `prismic.layout.en-us.0.data.main_navigation.0.main_navigation_link ` instead of `prismic.layout["en-us"].data.main_navigation.main_navigation_link` as mentioned in the documentation ?

**Comment by haroldao** [comment]
![image](https://user-images.githubusercontent.com/36776278/157321229-63d9c8ce-f7df-4713-bcff-c1554e279fdf.png)

**Comment by haroldao** [comment]
![image](https://user-images.githubusercontent.com/36776278/157321402-226dcad0-cdec-4805-8f13-1db7908f80e8.png)

**Comment by lihbr** [comment]
Maybe! I'm not familiar with liquid, the documentation is written in nunjuck ☺️

If `.en-us.` works and `["en-us"].` doesn't, it's perfectly fine to stick with `.en-us.` then I guess~
